server:
  port: 8081

spring:
  application:
    name: pass-batch
  datasource:
    url: jdbc:mysql://localhost:3306/batch?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari: # Spring Boot2부터 default DBCP는 hikariCP입니다.
      maximum-pool-size: 20             # pool에 보관 가능한 최대 connection 수
      # minimum-idle: 20                  maximum-pool-size를 따라가므로 설정을 생략합니다.

  jpa:
    open-in-view: false
    show-sql: true         # 쿼리를 표준 출력으로
    properties:
      hibernate:
        format_sql: false  # 아름답게 출력
        hibernate.default_batch_fetch_size: 100


  batch:
    job:
      enabled: false # 기본값 true는 Spring Boot 실행 시 등록되어 있는 Job들이 실행됩니다.
    jdbc:
      # Batch에 사용되는 SQL 초기화 스크립트를 실행합니다. 임베디드인 경우에는 기본적으로 실행하는데, always 설정을 하면 임베디드 타입처럼 항상 활성화시킬 수 있습니다.
      # 초기 수행한 이후에는 꺼두어도 됩니다.
      initialize-schema: always

logging:
  level:
    com.fc.board: debug
    #request, response log
    org.springframework.web.servlet: debug
    #jpa query log debug 중 binding query parameter ? 으로 나타나는 것을 관찰할 수 있게함
    org.hibernate.type.descriptor.sql.BasicBinder: trace
